# Tile Slicer Config
ningester:
  tile_slicer: sliceFileByTilesDesired
  sliceFileByTilesDesired:
    tilesDesired: 1296
    timeDimension: time
    dimensions:
      - lat
      - lon
---
# Tile processors configuration
ningester:
  tile_processors:
    - pythonChainProcessor
    - generateTileId
    - addTimeFromGranuleName
    - addDayOfYearAttribute
    - addDatasetName
  pythonChainProcessor:
    enabled:
    processor_list:
      -
        name: GridReadingProcessor
        config:
          latitude: lat
          longitude: lon
          time: time
          variable_to_read: analysed_sst
      -
        name: EmptyTileFilter
      -
        name: KelvinToCelsius
      -
        name: TileSummarizingProcessor
        config:
          stored_var_name: analysed_sst
  generateTileId:
    enabled:
  addTimeFromGranuleName:
    enabled:
    regex: ^.*(\d{3})\.
    dateFormat: DDD
  addDayOfYearAttribute:
    enabled:
    regex: ^.*(\d{3})\.
  addDatasetName:
    enabled:
    datasetName: AVHRR_OI_L4_GHRSST_NCEI_CLIM
---
# Tile writer configuration
ningester:
  tile_writer:
    data_store: cassandraStore
    metadata_store: solrStore
---
# Connection settings for the test profile
spring:
    profiles:
      - test
      - local
    data:
      cassandra:
        keyspaceName: nexustiles
        contactPoints: 127.0.0.1
      solr:
        host: http://127.0.0.1:8983/solr/

datasource:
  solrStore:
    collection: nexustiles